services:
  postgres:
    container_name: postgres_dashboard
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  api:
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      CORS_ORIGIN: "${CORS_ORIGIN}"
      JWT_SECRET: "${JWT_SECRET}"
      PRISMA_SCHEMA_PATH: "./prisma/schema.prisma" 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres: