name: CI/CD Pipeline

on:
  push:
    branches: 
      - main 
      - dev
      - feature/* 
      - fix/*
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Generate Prisma Client
        run: bunx prisma generate
      
      - name: Lint code
        run: bun run lint
      
      - name: Check type
        run: bun run typecheck
        
  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
        
      - name: Generate Prisma Client
        run: bunx prisma generate
        
      - name: Build project
        run: bun run build